{anr: '', anrgoon: 1, blacklist: '', bwlisfile: '', crashgoon: 1, deviceid: '', logv: -v,
  monkeyscript: '', pkg: '', runtimes: '200000', savecompu: 0, savelogcat: 1, securgoon: 1,
  seed: '', self: '', seperateerr: 1, throttle: 1000, writelist: ''}
